# Generated by Django 4.2.2 on 2023-07-03 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_product_p_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='P_img',
            new_name='p_img',
        ),
    ]
